# Type stubs for PyPDF2
from typing import Any, List, Optional, Union, BinaryIO
from pathlib import Path

class PdfReader:
    def __init__(self, stream: Union[str, Path, BinaryIO], **kwargs: Any) -> None: ...
    
    @property
    def pages(self) -> List[PageObject]: ...
    
    @property
    def metadata(self) -> Optional[dict[str, Any]]: ...
    
    def get_page(self, page_number: int) -> PageObject: ...

class PageObject:
    def extract_text(self, **kwargs: Any) -> str: ...
    def rotate(self, angle: float) -> PageObject: ...
    def scale(self, sx: float, sy: float) -> PageObject: ...
    
    @property
    def mediabox(self) -> Any: ...

class PdfWriter:
    def __init__(self) -> None: ...
    def add_page(self, page: PageObject) -> None: ...
    def write(self, stream: BinaryIO) -> None: ...

class PdfMerger:
    def __init__(self) -> None: ...
    def append(self, fileobj: Any, **kwargs: Any) -> None: ...
    def merge(self, position: int, fileobj: Any, **kwargs: Any) -> None: ...
    def write(self, fileobj: BinaryIO) -> None: ...
    def close(self) -> None: ...

# Legacy aliases for backward compatibility
PdfFileReader = PdfReader
PdfFileWriter = PdfWriter
PdfFileMerger = PdfMerger
